### ISSUE TITLE
Trocar a logo do if do Header

### ISSUE THREAD

**Issue by bruno-rodrigues0** [bruno-rodrigues0/COLSIF#44]
# Alteração de logo

---

A logo do if n está contrastando com o fundo do Header

![image](https://github.com/bruno-rodrigues0/COLSIF/assets/119943937/576ce2f3-0b53-4bad-b929-fb18717963c5)

*Tá feio 👎🏽*

**Comment by msantos7gabriel** [comment]
ta meio paia mesmo vou ver com os mano da **issue #46**  podem fazer isso aki tb

**Comment by msantos7gabriel** [comment]
@bruno-rodrigues0 ce tem uma ideia do q cê acha q ficaria legal ?

**Comment by bruno-rodrigues0** [comment]
> @bruno-rodrigues0 ce tem uma ideia do q cê acha q ficaria legal ?
> 

pensei em nada

**Comment by msantos7gabriel** [comment]
ai é foda 

 vou tirar o fundo deixar so o branco
