### ISSUE TITLE
Criar logo do evento e o Favicon

### ISSUE THREAD

**Issue by bruno-rodrigues0** [bruno-rodrigues0/COLSIF#46]
# Logo do evento

---

Eu acho que essa logo ja foi criada, então se a boa alma que as possui puder mandar pra gente ai 😄

**Comment by msantos7gabriel** [comment]
É bom não so criar a logo como o Favicon.ico

**Comment by joaopedrosbt** [comment]
A issue da logo aq

**Comment by bruno-rodrigues0** [comment]
> É bom não so criar a logo como o Favicon.ico

Exato, não temos o Favicon (Icone que fica no topo da página)

![image](https://github.com/bruno-rodrigues0/COLSIF/assets/119943937/25b6d386-683d-4811-97eb-44aac68a6813)

**Comment by joaopedrosbt** [comment]
Vo fazer dps uma massa

**Comment by guilherme-pimentel** [comment]
Guilherme Bezerra está responsável

**Comment by msantos7gabriel** [comment]
Pronto agr os dois fofos tão responsaveis

**Comment by msantos7gabriel** [comment]
> Guilherme Bezerra está responsável

Agr ce ta responsavel

**Comment by gustavo-robertoo** [comment]
Gustavo Roberto está responsável
