### ISSUE TITLE
Comentar o Projeto

### ISSUE THREAD

**Issue by msantos7gabriel** [bruno-rodrigues0/COLSIF#47]
# Comentário no projeto 
Atualmente no nosso projeto não há comentários impossibilitando a colaboração 

Peço ajuda para esse trabalho de comentários

Não me **importa o método** e sim o **Resultado**

To-Do List: 

1. Paginas HTML:
      - [x] #48
      - [x] #50
      - [x] #51
      - [x] #53
   
1. Paginas CSS:
      - [x] #58
      - [x] #59
      - [x] #60
      - [x] #61
      - [x] #62
      - [x] #49
   
   
Agradeço pela Colaboração
---
### Gabriel

**Comment by bruno-rodrigues0** [comment]
to colado aq

**Comment by msantos7gabriel** [comment]
terminada a documentação
