### ISSUE TITLE
Adicionar fotos no carrossel de imagens da index.html 

### ISSUE THREAD

**Issue by msantos7gabriel** [bruno-rodrigues0/COLSIF#69]
![image](https://github.com/bruno-rodrigues0/COLSIF/assets/113394709/53c17ddc-b538-43ba-9a2d-0d82290c5c8f)

**Comment by bruno-rodrigues0** [comment]
a gente ja tem as imgs?

**Comment by msantos7gabriel** [comment]
eu pedi no grupo da sala e nada

**Comment by msantos7gabriel** [comment]
Pelo q eu tenho aki é coisa do insta da escola: [Foto](https://www.instagram.com/p/C4MPkPsr29w/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==) [Video](https://www.instagram.com/reel/C4MP4zILb1R/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)

**Comment by bruno-rodrigues0** [comment]
> ## Pelo q eu tenho aki é coisa do insta da escola: [Foto](https://www.instagram.com/p/C4MPkPsr29w/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==) [Video](https://www.instagram.com/reel/C4MP4zILb1R/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)
> e esse video bem paioso do [insta do if](https://www.instagram.com/reel/C4QUYnaA4q9/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)

da bom pegar essas img do insta msm

**Comment by msantos7gabriel** [comment]
catar essa porra ai
